# Generated by Django 4.0.4 on 2022-04-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('duracao', models.DateField()),
                ('dataCadastro', models.DateField()),
                ('funcao', models.CharField(max_length=100)),
            ],
        ),
    ]
